bancoDePerguntas = [
    # Perguntas sobre direção
    {"pergunta": "Quem é o diretor de O Poderoso Chefão?", "tipo": ["diretor"]},
    {"pergunta": "Quem dirigiu Titanic?", "tipo": ["diretor"]},
    {"pergunta": "De quem foi a direção de Clube da Luta?", "tipo": ["diretor"]},
    {"pergunta": "Qual o nome do diretor de Interestelar?", "tipo": ["diretor"]},
    {"pergunta": "Quem fez a direção de Pulp Fiction?", "tipo": ["diretor"]},
    {"pergunta": "Diretor do filme Cidadão Kane?", "tipo": ["diretor"]},
    {"pergunta": "Quem está creditado como diretor em Os Suspeitos?", "tipo": ["diretor"]},
    {"pergunta": "Quem realizou a direção de O Iluminado?", "tipo": ["diretor"]},
    {"pergunta": "Nome do diretor responsável por Parasita?", "tipo": ["diretor"]},
    {"pergunta": "Quem comandou a direção de O Senhor dos Anéis?", "tipo": ["diretor"]},
    {"pergunta": "Quem assina a direção de Psicose?", "tipo": ["diretor"]},
    {"pergunta": "Direção de Curtindo a Vida Adoidado?", "tipo": ["diretor"]},
    {"pergunta": "Quem esteve à frente da direção de Blade Runner?", "tipo": ["diretor"]},
    {"pergunta": "Quem dirigiu o filme A Origem?", "tipo": ["diretor"]},
    {"pergunta": "De quem foi a direção artística de O Labirinto do Fauno?", "tipo": ["diretor"]},
    {"pergunta": "Quem ficou responsável pela direção de Django Livre?", "tipo": ["diretor"]},
    {"pergunta": "Quem assina a direção de Os Infiltrados?", "tipo": ["diretor"]},
    {"pergunta": "Diretor por trás de A Lista de Schindler?", "tipo": ["diretor"]},
    {"pergunta": "Quem esteve na cadeira de direção de Gladiador?", "tipo": ["diretor"]},
    {"pergunta": "Quem realizou a direção cinematográfica de Seven?", "tipo": ["diretor"]},

    # Perguntas sobre elenco
    {"pergunta": "Quem são os atores principais de O Rei Leão?", "tipo": ["ator"]},
    {"pergunta": "Qual o elenco de Forrest Gump?", "tipo": ["ator"]},
    {"pergunta": "Quem atua em Os Caçadores da Arca Perdida?", "tipo": ["ator"]},
    {"pergunta": "Atores principais de O Silêncio dos Inocentes?", "tipo": ["ator"]},
    {"pergunta": "Quem está no elenco de De Volta para o Futuro?", "tipo": ["ator"]},
    {"pergunta": "Protagonistas de La La Land?", "tipo": ["ator"]},
    {"pergunta": "Quem são os atores de O Grande Truque?", "tipo": ["ator"]},
    {"pergunta": "Elenco principal de Os Oito Odiados?", "tipo": ["ator"]},
    {"pergunta": "Quem faz parte do casting de Os Suspeitos?", "tipo": ["ator"]},
    {"pergunta": "Atores que participam de Scarface?", "tipo": ["ator"]},
    {"pergunta": "Quem está no elenco de O Resgate do Soldado Ryan?", "tipo": ["ator"]},
    {"pergunta": "Protagonistas de Bastardos Inglórios?", "tipo": ["ator"]},
    {"pergunta": "Quem atua em O Sexto Sentido?", "tipo": ["ator"]},
    {"pergunta": "Atores principais de O Iluminado?", "tipo": ["ator"]},
    {"pergunta": "Quem faz parte do elenco de Amnésia?", "tipo": ["ator"]},
    {"pergunta": "Quem são os atores de Os Sete Samurais?", "tipo": ["ator"]},
    {"pergunta": "Elenco de O Profissional?", "tipo": ["ator"]},
    {"pergunta": "Quem atua em O Pianista?", "tipo": ["ator"]},
    {"pergunta": "Atores principais de O Exterminador do Futuro?", "tipo": ["ator"]},
    {"pergunta": "Quem está no casting de Matrix?", "tipo": ["ator"]},

    # Perguntas sobre gênero
    {"pergunta": "Qual o gênero do filme Tubarão?", "tipo": ["genero"]},
    {"pergunta": "Que tipo de filme é Corra?", "tipo": ["genero"]},
    {"pergunta": "Gênero cinematográfico de O Iluminado?", "tipo": ["genero"]},
    {"pergunta": "Classificação por gênero de O Labirinto do Fauno?", "tipo": ["genero"]},
    {"pergunta": "Que estilo de filme é Amelie Poulain?", "tipo": ["genero"]},
    {"pergunta": "Gênero predominante em Os Vingadores?", "tipo": ["genero"]},
    {"pergunta": "Tipo de filme: O Poderoso Chefão?", "tipo": ["genero"]},
    {"pergunta": "Qual a categoria de Curtindo a Vida Adoidado?", "tipo": ["genero"]},
    {"pergunta": "Gênero principal de O Sexto Sentido?", "tipo": ["genero"]},
    {"pergunta": "Que tipo de produção é Pulp Fiction?", "tipo": ["genero"]},
    {"pergunta": "Classificação por gênero de Psicose?", "tipo": ["genero"]},
    {"pergunta": "Gênero cinematográfico de Cidade de Deus?", "tipo": ["genero"]},
    {"pergunta": "Que estilo de filme é O Fabuloso Destino de Amélie Poulain?", "tipo": ["genero"]},
    {"pergunta": "Gênero de O Silêncio dos Inocentes?", "tipo": ["genero"]},
    {"pergunta": "Tipo de produção de O Rei Leão?", "tipo": ["genero"]},

    # Perguntas sobre ano
    {"pergunta": "Em que ano foi lançado Titanic?", "tipo": ["ano"]},
    {"pergunta": "Ano de lançamento de O Poderoso Chefão?", "tipo": ["ano"]},
    {"pergunta": "Quando estreou Matrix nos cinemas?", "tipo": ["ano"]},
    {"pergunta": "Data de lançamento de De Volta para o Futuro?", "tipo": ["ano"]},
    {"pergunta": "Em que ano saiu Jurassic Park?", "tipo": ["ano"]},
    {"pergunta": "Ano de produção de E.T. - O Extraterrestre?", "tipo": ["ano"]},
    {"pergunta": "Quando foi lançado Star Wars: Episódio IV?", "tipo": ["ano"]},
    {"pergunta": "Em que ano chegou aos cinemas O Senhor dos Anéis?", "tipo": ["ano"]},
    {"pergunta": "Ano de estreia de Blade Runner?", "tipo": ["ano"]},
    {"pergunta": "Quando foi produzido Psicose?", "tipo": ["ano"]},
    {"pergunta": "Data de lançamento de Curtindo a Vida Adoidado?", "tipo": ["ano"]},
    {"pergunta": "Em que ano foi feito Cidadão Kane?", "tipo": ["ano"]},
    {"pergunta": "Ano de lançamento de Os Caçadores da Arca Perdida?", "tipo": ["ano"]},
    {"pergunta": "Quando estreou O Resgate do Soldado Ryan?", "tipo": ["ano"]},
    {"pergunta": "Em que ano foi lançado O Iluminado?", "tipo": ["ano"]},

    # Perguntas compostas
    {"pergunta": "Quem dirigiu e quais os atores de O Poderoso Chefão?", "tipo": ["diretor", "ator"]},
    {"pergunta": "Qual o gênero e ano de lançamento de Titanic?", "tipo": ["genero", "ano"]},
    {"pergunta": "Diretor e ano de lançamento de Matrix?", "tipo": ["diretor", "ano"]},
    {"pergunta": "Atores e gênero de Clube da Luta?", "tipo": ["ator", "genero"]},
    {"pergunta": "Me fale sobre o diretor e o ano de Star Wars", "tipo": ["diretor", "ano"]},
    {"pergunta": "Quem são os atores e qual o gênero de La La Land?", "tipo": ["ator", "genero"]},
    {"pergunta": "Ano e diretor de Os Infiltrados?", "tipo": ["ano", "diretor"]},
    {"pergunta": "Gênero e atores principais de O Grande Truque?", "tipo": ["genero", "ator"]},
    {"pergunta": "Quem dirigiu e quando foi lançado Psicose?", "tipo": ["diretor", "ano"]},
    {"pergunta": "Atores e ano de lançamento de Scarface?", "tipo": ["ator", "ano"]},
    {"pergunta": "Diretor e gênero de Parasita?", "tipo": ["diretor", "genero"]},
    {"pergunta": "Me informe o ano e os atores de O Rei Leão", "tipo": ["ano", "ator"]},
    {"pergunta": "Qual o diretor e o gênero de Amnésia?", "tipo": ["diretor", "genero"]},
    {"pergunta": "Quando foi lançado e quem são os atores de Os Suspeitos?", "tipo": ["ano", "ator"]},
    {"pergunta": "Gênero e diretor de O Labirinto do Fauno?", "tipo": ["genero", "diretor"]},
    {"pergunta": "Quem atua e quem dirigiu Bastardos Inglórios?", "tipo": ["ator", "diretor"]},
    {"pergunta": "Ano e gênero de O Pianista?", "tipo": ["ano", "genero"]},
    {"pergunta": "Direção e elenco de Os Oito Odiados?", "tipo": ["diretor", "ator"]},
    {"pergunta": "Data de lançamento e atores de O Exterminador do Futuro?", "tipo": ["ano", "ator"]},
    {"pergunta": "Quem realizou a direção e qual o gênero de Seven?", "tipo": ["diretor", "genero"]},
    {"pergunta": "Informe o ano e o diretor de Gladiador", "tipo": ["ano", "diretor"]},
    {"pergunta": "Quem está no elenco e qual o gênero de A Origem?", "tipo": ["ator", "genero"]},
    {"pergunta": "Diretor e data de lançamento de Django Livre?", "tipo": ["diretor", "ano"]},
    {"pergunta": "Atores principais e ano de E.T.?", "tipo": ["ator", "ano"]},
    {"pergunta": "Gênero e diretor de Cidade de Deus?", "tipo": ["genero", "diretor"]},
    {"pergunta": "Quem dirigiu e quem atua em Os Sete Samurais?", "tipo": ["diretor", "ator"]},
    {"pergunta": "Ano e gênero de O Profissional?", "tipo": ["ano", "genero"]},
    {"pergunta": "Elenco e diretor de O Fabuloso Destino de Amélie Poulain?", "tipo": ["ator", "diretor"]},
    {"pergunta": "Data de lançamento e gênero de Corra?", "tipo": ["ano", "genero"]},
    {"pergunta": "Quem fez a direção e quais os atores de Jurassic Park?", "tipo": ["diretor", "ator"]},

    # Perguntas gerais
    {"pergunta": "Me fale sobre o filme O Poderoso Chefão", "tipo": ["geral"]},
    {"pergunta": "Dê-me informações sobre Titanic", "tipo": ["geral"]},
    {"pergunta": "Conte-me sobre Matrix", "tipo": ["geral"]},
    {"pergunta": "Resumo de Clube da Luta", "tipo": ["geral"]},
    {"pergunta": "Detalhes sobre Interestelar", "tipo": ["geral"]},
    {"pergunta": "Informações sobre Pulp Fiction", "tipo": ["geral"]},
    {"pergunta": "O que sabe sobre Cidadão Kane?", "tipo": ["geral"]},
    {"pergunta": "Me dê detalhes de Os Suspeitos", "tipo": ["geral"]},
    {"pergunta": "Fale sobre O Iluminado", "tipo": ["geral"]},
    {"pergunta": "Me informe sobre Parasita", "tipo": ["geral"]},
    {"pergunta": "Conte-me detalhes de O Senhor dos Anéis", "tipo": ["geral"]},
    {"pergunta": "Resumo de Psicose", "tipo": ["geral"]},
    {"pergunta": "Dados sobre Curtindo a Vida Adoidado", "tipo": ["geral"]},
    {"pergunta": "O que pode me dizer sobre Blade Runner?", "tipo": ["geral"]},
    {"pergunta": "Informações gerais de A Origem", "tipo": ["geral"]},
    {"pergunta": "Fale um pouco sobre O Labirinto do Fauno", "tipo": ["geral"]},
    {"pergunta": "Me conte sobre Django Livre", "tipo": ["geral"]},
    {"pergunta": "Detalhes de Os Infiltrados", "tipo": ["geral"]},
    {"pergunta": "O que sabe sobre A Lista de Schindler?", "tipo": ["geral"]},
    {"pergunta": "Me fale sobre Gladiador", "tipo": ["geral"]}
]